name: AWS Deploy

on:
  push:
    branches:
      - master
      - stage
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Secrets to file
        run: |
          mkdir ./aws-prod/certs
          echo ${{ secrets.CRT_CRT }} | base64 -d > ./aws-prod/certs/crt.crt
          echo ${{ secrets.CRT_KEY }} | base64 -d > ./aws-prod/certs/key.key
          echo ${{ secrets.ENV_FILE }} | base64 -d > ./aws-prod/.env
          echo ${{ secrets.SSH_PRIVATE_KEY }} | base64 -d > ./ip_rsa_aws
          
      - name: Copy file to AWS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key_path: "./ip_rsa_aws"
          port: 22
          source: "
          aws-prod/traefik/traefik.yml,
          aws-prod/.env,
          aws-prod/docker-compose-prod.yml,
          aws-prod/certs/crt.crt,
          aws-prod/certs/key.key"
          target: "/opt/chaskiq-docker/"
      - name: RUN deploy
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: "./ip_rsa_aws"
      - run: ssh ${{ secrets.SSH_HOST }} pwd