name: Push Docker Image

on:
  push:
    branches:
      - master
      - stage
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login into Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v2

      - name: Get Short SHA
        id: vars
        run: |
          echo ::set-output name=short_sha::$(git rev-parse --short=7 ${{ github.sha }})

      - name: Build the Docker image
        run: |
          docker build --build-arg APP_ENV=production \
               --build-arg RUBY_VERSION=2.7.5 \
               --build-arg PG_MAJOR=11 \
               --build-arg NODE_MAJOR=16 \
               --build-arg YARN_VERSION=1.13.0 \
               --build-arg BUNDLER_VERSION=2.3.15 \
               -t cience/go-chat \
               .

      - name: Tag and Push Docker image
        if: github.event_name == 'push'
        run: |
          docker tag cience/go-chat cience/go-chat:$SHORT_SHA
          docker push cience/go-chat:$SHORT_SHA
          echo "SHORT_SHA: ${SHORT_SHA}"
        env:
          SHORT_SHA: ${{ steps.vars.outputs.short_sha }}

      - name: Tag LATEST and Push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          docker tag cience/go-chat cience/go-chat:latest
          docker push cience/go-chat:latest
          echo "LATEST deployed!"

      - name: Tag AWS-PROD-IMG and Push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          docker tag cience/go-chat cience/go-chat:aws-prod-img
          docker push cience/go-chat:aws-prod-img
          echo "AWS-PROD-IMG deployed!"

      - name: Tag RELEASE and Push Docker image
        if: github.event_name	== 'release'
        run: |
          docker tag cience/go-chat cience/go-chat:${{ github.ref_name }}
          docker push cience/go-chat:${{ github.ref_name }}
          echo "${{ github.ref_name }} deployed!"

      # - name: RUN deploy
      # - run: echo ${{ secrets.SSH_PRIVATE_KEY }} | base64 -d > ~/.ssh/id_rsa
      # - run: chmod 600 ~/.ssh/id_rsa
      # - run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} ~/deploy.sh